version: '2'

services:
   db:
     image: mysql:5.7
     container_name: wp-db
     ports:
       - "3306:3306"
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     env_file: .env
     privileged: true

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     container_name: wp
     ports:
       - "80:80"
     restart: always
     working_dir: /var/www/html
     volumes:
       - /Users/hiroshima/develop/wp/html/:/var/www/html/
       - /Users/hiroshima/develop/wp/.docker/log:/tmp/log
       - /Users/hiroshima/develop/wp/.docker/backup:/tmp/backup
     environment:
       WORDPRESS_DB_HOST: db:3306
     env_file: .env
     privileged: true

volumes:
    db_data:
